import { Parser } from '../src/index.ts'
import { describe, it } from 'node:test'
import { equal } from 'node:assert'
import { mkdir, rmdir, stat, unlink, writeFile } from 'node:fs/promises'

describe('chmod - failure cases', () => {
  it('non-existing-file', async () => {
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('741', 'non-existing-file')
    equal(caught, undefined)
    executor.on('error', (reason: Error) => caught = reason)
    const err = await executor.executeAsync()
    equal(err instanceof Error, true)
    equal(caught as unknown instanceof Error, true)
    equal(err, caught)
  })
})

describe('chmod - successful cases', () => {
  it('+x', async () => {
    await mkdir('tmp1')
    for (const name of ['foo', 'bar'])
      await writeFile(`tmp1/${name}`, name)
    await mkdir('tmp1/baz')
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('+x', 'tmp1/foo', 'tmp1/bar', 'tmp1/baz')
    equal(caught, undefined)
    executor.on('error', (reason: Error) => caught = reason)
    const err = await executor.executeAsync()
    equal(caught, undefined)
    equal(err instanceof Error, false)
    equal(err, true)
    const stats = await stat('tmp1/foo')
    equal(stats instanceof Error, false)
    if (!(stats instanceof Error))
      equal(stats.mode, 0o100755)
    await rmdir('tmp1/baz')
    for (const name of ['foo', 'bar'])
      await unlink(`tmp1/${name}`)
    await rmdir('tmp1')
  })
  it('-R +X', async () => {
    await mkdir('tmp2')
    await mkdir('tmp2/foo')
    await mkdir('tmp2/foo/bar')
    await writeFile('tmp2/foo/bar/baz', 'this is baz\n')
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('-R', '+X', 'tmp2')
    const success = await executor.executeAsync()
    equal(caught, undefined)
    equal(success, true)
    const bar = await stat('tmp2/foo/bar')
    equal(bar instanceof Error, false)
    const baz = await stat('tmp2/foo/bar/baz')
    equal(baz instanceof Error, false)
    if (!(bar instanceof Error || baz instanceof Error)) {
      equal(bar.mode, 0o040755)
      equal(baz.mode, 0o100644)
    }
    await unlink('tmp2/foo/bar/baz')
    await rmdir('tmp2/foo/bar')
    await rmdir('tmp2/foo')
    await rmdir('tmp2')
  })
  it('a+wx', async () => {
    await mkdir('tmp3')
    await writeFile('tmp3/foo', '#!/bin/sh\necho this is foo\n')
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('a+wx', 'tmp3/foo')
    equal(caught, undefined)
    executor.on('error', (reason: Error) => caught = reason)
    const err = await executor.executeAsync()
    equal(caught, undefined)
    equal(err instanceof Error, false)
    equal(err, true)
    const stats = await stat('tmp3/foo')
    equal(stats instanceof Error, false)
    if (!(stats instanceof Error))
      equal(stats.mode, 0o100777)
    await unlink('tmp3/foo')
    await rmdir('tmp3')
  })
  it('u-r,g+w,o-x', async () => {
    await mkdir('tmp4')
    await writeFile('tmp4/foo', 'this is foo\n')
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('u-r,g+w,o-x', 'tmp4/foo')
    equal(caught, undefined)
    executor.on('error', (reason: Error) => caught = reason)
    const err = await executor.executeAsync()
    equal(caught, undefined)
    equal(err instanceof Error, false)
    equal(err, true)
    const stats = await stat('tmp4/foo')
    equal(stats instanceof Error, false)
    if (!(stats instanceof Error))
      equal(stats.mode, 0o100264)
    await unlink('tmp4/foo')
    await rmdir('tmp4')
  })
  it('o-r,o+w,o+x', async () => {
    await mkdir('tmp5')
    await writeFile('tmp5/foo', 'this is foo\n')
    const parser = new Parser()
    let caught: Error | undefined
    parser.on('error', (reason: Error) => caught = reason)
    const executor = parser.parse('o-r,o+w,o+x', 'tmp5/foo')
    equal(caught, undefined)
    executor.on('error', (reason: Error) => caught = reason)
    const err = await executor.executeAsync()
    equal(caught, undefined)
    equal(err instanceof Error, false)
    equal(err, true)
    const stats = await stat('tmp5/foo')
    equal(stats instanceof Error, false)
    if (!(stats instanceof Error))
      equal(stats.mode, 0o100643)
    await unlink('tmp5/foo')
    await rmdir('tmp5')
  })
})
