jobs:
  build:
    continue-on-error: true
    name: Build on Node.js ${{ matrix.node }}
    outputs:
      result: ${{ steps.build.outputs.result }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '12.22.7'
          - '14.17.6'
          - '16.13.1'
          - '17.2.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - id: build
        name: Build
        run: npm run build && echo "::set-output name=result::success"
  coverage:
    continue-on-error: true
    name: Check code coverages on Node.js ${{ matrix.node }}
    outputs:
      result: ${{ steps.coverage.outputs.result }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '12.22.7'
          - '14.17.6'
          - '16.13.1'
          - '17.2.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - id: coverage
        name: Test
        run: npm test && echo "::set-output name=result::success"
      - if: ${{ always() }}
        name: Archive code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: coverage
  test:
    name: Aggregate results
    needs:
      - build
      - coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check build result
        run: test "${{ needs.build.outputs.result }}" = "success" || { echo "\x1b[31mFailed to build\x1b[m"; exit 1; }
      - name: Check code coverages result
        run: test "${{ needs.coverage.outputs.result }}" = "success" || { echo "\x1b[31mFailed to check code coverages\x1b[m"; exit 1; }
name: Test
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE'
  push:
    branches:
      - devel
      - main
      - release
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE'
